import type { Metadata } from "next";
import { Syne_Mono } from "next/font/google";
import "./globals.css";

const syneMono = Syne_Mono({
  weight: "400",
  style: "normal",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${syneMono.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
